import { jsPDF } from "jspdf";
import type { Pnl } from "./reports";

// Renders the same revenue/expenses numbers the Reports page shows as a
// simple, single-report PDF — used behind the share-link route
// (src/app/api/reports/share/[token]) so a manager can hand this to
// someone (an accountant, a co-owner) without giving them KOP access at
// all. Plain text layout on purpose: this is a numbers hand-off, not a
// branded document, and jsPDF's built-in fonts need no extra font files
// bundled into the serverless function (pdfkit-style libraries that read
// .afm files from disk hit exactly that problem on Vercel — see the
// build log's operational note #2 for the same class of issue with
// drizzle's migration files).
export function renderPnlPdf({
  studioName,
  currency,
  from,
  to,
  pnl,
}: {
  studioName: string;
  currency: string;
  from: string;
  to: string;
  pnl: Pnl;
}): Buffer {
  const money = (n: number) =>
    new Intl.NumberFormat("en-US", { style: "currency", currency }).format(n);

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const left = 48;
  const right = 547;
  let y = 56;

  const ensureRoom = (needed = 16) => {
    if (y + needed > 780) {
      doc.addPage();
      y = 56;
    }
  };

  doc.setFontSize(18);
  doc.text(`${studioName} — Revenue & Expenses`, left, y);
  y += 20;

  doc.setFontSize(11);
  doc.setTextColor(110);
  doc.text(`${from} – ${to}`, left, y);
  doc.setTextColor(0);
  y += 32;

  doc.setFontSize(13);
  doc.text("Summary", left, y);
  y += 18;
  doc.setFontSize(11);
  doc.text(`Revenue`, left, y);
  doc.text(money(pnl.totalRevenue), right, y, { align: "right" });
  y += 16;
  doc.text(`Expenses`, left, y);
  doc.text(money(pnl.totalExpenses), right, y, { align: "right" });
  y += 16;
  doc.setFont("helvetica", "bold");
  doc.text(`Net`, left, y);
  doc.text(money(pnl.net), right, y, { align: "right" });
  doc.setFont("helvetica", "normal");
  y += 32;

  doc.setFontSize(13);
  doc.text("Revenue by source", left, y);
  y += 18;
  doc.setFontSize(10);
  if (pnl.revenueBySource.size === 0) {
    doc.setTextColor(140);
    doc.text("No revenue in this period.", left, y);
    doc.setTextColor(0);
    y += 16;
  } else {
    for (const [source, v] of pnl.revenueBySource) {
      ensureRoom();
      doc.text(`${source.replace(/_/g, " ")} (${v.count})`, left, y);
      doc.text(money(v.total), right, y, { align: "right" });
      y += 15;
    }
  }
  y += 18;

  doc.setFontSize(13);
  doc.text("Expenses by category", left, y);
  y += 18;
  doc.setFontSize(10);
  if (pnl.expensesByCategory.size === 0) {
    doc.setTextColor(140);
    doc.text("No expenses in this period.", left, y);
    doc.setTextColor(0);
    y += 16;
  } else {
    for (const [category, v] of pnl.expensesByCategory) {
      ensureRoom();
      doc.text(`${category.replace(/_/g, " ")} (${v.count})`, left, y);
      doc.text(money(v.total), right, y, { align: "right" });
      y += 15;
    }
  }

  ensureRoom(24);
  y += 16;
  doc.setFontSize(8);
  doc.setTextColor(160);
  doc.text(`Generated by KOP on ${new Date().toISOString().slice(0, 10)}.`, left, y);

  return Buffer.from(doc.output("arraybuffer"));
}
